version: "3"
services:
  back:
    image: tayssi/myboost-project3:latest
    build: .
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongo:27017
    ports:
      - "9090:9090"
    networks:
      - myboost
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    ports:
      - "2017:27017"
    volumes:
      - db:/data/db
    networks:
      - myboost
volumes:
  db:
networks:
  myboost: